[package]
name = "warpx"
version.workspace = true
edition = "2024"
authors.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
command = { path = "../command" }
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
toml = { version = "0.8", default-features = false, features = ["parse"] }

[dev-dependencies]
tempfile.workspace = true
