on:
  pull_request:
    branches:
      - "joe/main"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

name: Warp CI (macOS)

env:
  CARGO_TERM_COLOR: always
  NEXTEST_PROFILE: ci
  WORKSPACE_TEST_ARGS: --workspace --locked --exclude command-signatures-v2
  RUSTFLAGS: -C debuginfo=line-tables-only --cfg=web_sys_unstable_apis

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run MacOS tests
    timeout-minutes: 30
    runs-on: [self-hosted, warpx-mac]
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/prepare_environment
        with:
          target_os: macos
          is_self_hosted: "true"
          install_test_deps: true

      - name: Echo Shells
        id: echo_shells
        shell: bash
        run: |
          DEFAULT_BASH_PATH="$(command -pv bash)"
          echo "default_bash_path=$DEFAULT_BASH_PATH" >> $GITHUB_OUTPUT

          ZSH_PATH="$(which zsh || echo /bin/zsh)"
          echo "zsh_path=$ZSH_PATH" >> $GITHUB_OUTPUT

          FISH_PATH="$(which fish || echo "")"
          echo "fish_path=$FISH_PATH" >> $GITHUB_OUTPUT

      - name: Install cargo nextest
        shell: bash
        run: |
          command -v cargo-nextest >/dev/null 2>&1 || cargo install cargo-nextest --locked

      - name: Compile tests
        run: cargo nextest run ${{ env.WORKSPACE_TEST_ARGS }} --no-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        if: success()
        run: cargo nextest run ${{ env.WORKSPACE_TEST_ARGS }} -E "not package(integration)"
        env:
          WARP_SHELL_PATH: ${{ steps.echo_shells.outputs.zsh_path }}

      - name: Run shell-agnostic integration tests
        if: success() || failure()
        run: cargo nextest run ${{ env.WORKSPACE_TEST_ARGS }} -E "package(integration) and not test(shell_integration_tests) and not test(/_ssh_/)"
        env:
          WARP_SHELL_PATH: ${{ steps.echo_shells.outputs.zsh_path }}

      - name: Run shell integration tests (bash)
        if: success() || failure()
        run: cargo nextest run ${{ env.WORKSPACE_TEST_ARGS }} -E "package(integration) and test(shell_integration_tests)"
        env:
          WARP_SHELL_PATH: ${{ steps.echo_shells.outputs.default_bash_path }}

      - name: Run shell integration tests (zsh)
        if: success() || failure()
        run: cargo nextest run ${{ env.WORKSPACE_TEST_ARGS }} -E "package(integration) and test(shell_integration_tests)"
        env:
          WARP_SHELL_PATH: ${{ steps.echo_shells.outputs.zsh_path }}

      - name: Run shell integration tests (fish)
        if: (success() || failure()) && steps.echo_shells.outputs.fish_path != ''
        run: cargo nextest run ${{ env.WORKSPACE_TEST_ARGS }} -E "package(integration) and test(shell_integration_tests)"
        env:
          WARP_SHELL_PATH: ${{ steps.echo_shells.outputs.fish_path }}

      - name: Run doc tests
        if: success() || failure()
        run: cargo test ${{ env.WORKSPACE_TEST_ARGS }} --doc

      - name: Run completions-on-js tests
        if: success() || failure()
        run: cargo nextest run --locked -p warp_completer --features v2
